all: 
	g++ src/main.cpp src/simulator.cpp src/math.cpp -Wall -Wextra -pedantic -o sim -lgmp -lgmpxx -pthread -std=c++11 -ggdb
msd:
 g++ src/msd.cpp src/math.cpp -Wall -Wextra -lgmp -lgmpxx -std=c++11 -o msd
